#!/usr/bin/env bash
function essentials {
	case "$1" in
	check_eligibility)
		echo 'essentials check_eligibility'
		;;
	upload)
		echo "essentials upload $ap_human_name"
		echo "essentials upload path $ap_path"
		;;
	get_info)
		echo '[name]'
		echo 'essentials'
		echo '[description]'
		echo 'essentials'
		;;
	esac
}
